
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3307/gulimall_pms
    username: root
    password: "080655"
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: gulimall-prodcut
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
  # MapperScan
  # sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9004

feign:
  hystrix:
    enabled: true
